### ISSUE TITLE
Study Postgres SQL

### ISSUE THREAD

**Issue by mdzh10** [mdzh10/FinBot-AI-Powered-Chatbot-For-Personal-Finance-Management#13]

**Comment by Sriramrajivkarri12** [comment]
I had no experience with PostgresSQL but in general studying from online resources helped a lot with this. No issues with this

**Comment by vijaysai1102** [comment]
PostgreSQL is relatively new for me, but I don't think this was very difficult for me. I tried to learn all the queries that are important for our project.
