### ISSUE TITLE
Study Rest API with Python (FastAPI), CRUD operations

### ISSUE THREAD

**Issue by mdzh10** [mdzh10/FinBot-AI-Powered-Chatbot-For-Personal-Finance-Management#9]
Study basic CRUD operations using Python and FastAPI

**Comment by Sriramrajivkarri12** [comment]
Most of this was not a difficult task, because have some experience with this. 

But writing some of my own did take sometime, because my experience was not specific to rest api writing, especially fastapi.

**Comment by vijaysai1102** [comment]
This was not a very difficult task I would say but I tried to learn as much as possible that's is required to work with our project.
